/**
 * memoryd ↔ notifier-watcher wiring (ADR-004/010). Facts from
 * notifier-runtime (verified against their
 * registration.ts/peerProfileStore.ts + live run):
 *
 * - the REGISTRANT is the IAP envelope's from-personality:
 *   `iapeer send watcher --from claude-index` puts the trigger into
 *   `<index-cwd>/.iapeer/peer-profile.json` → `notifier.triggers[]`,
 *   owner=index (writing into a foreign profile is impossible by
 *   invariant). We register from INDEX — the consumer of memoryd events.
 *   `--from` takes the full IDENTITY `<runtime>-<personality>` (iapeer
 *   cli fact, verified by e2e §A: bare "index" → exit 1 «invalid --from
 *   identity»); the durable trigger's `owner` stays the parsed
 *   PERSONALITY ("index") — readWatcherTrigger matching is unaffected.
 * - replies (✓ registered / teaching errors / list) go to the
 *   from-personality SESSION, never to this script — so registration
 *   success is verified by READING THE STATE, not the reply:
 *   the durable file is a CANONICAL storage contract (sanctioned to
 *   parse): `notifier.triggers[]` entries `{role:"event", id, owner,
 *   target, script, …}`, match by id+owner+role.
 * - removal: `{"cmd":"unregister","id":"…"}` (role-scoped; not-found is
 *   soft).
 * - heartbeatSec is deliberately NOT declared: memoryd's stdout cadence is
 *   event-driven (quiet periods are normal) and every stdout line is
 *   forwarded to the target peer — a keepalive would spam the Index.
 *   Hang detection stays with the file heartbeat + verify (ADR-010).
 *   Confirmed by notifier-runtime (supervisor.ts facts): without
 *   heartbeatSec the watchdog never arms (no false restarts possible),
 *   while exit-detection ALWAYS works (any watcher-script exit → restart
 *   with backoff, crashloop → owner alert) — so "died as a process" is
 *   covered by the notifier and "hung silently" by our file heartbeat;
 *   no gap. There is no keepalive-without-forward channel today (a marker
 *   prefix is parked on their side until a second consumer appears).
 */

import fs from "node:fs";
import path from "node:path";
import { IAPEER_BIN, type Egress } from "./egress.js";
import { guardedWriteFileSync } from "@agfpd/iapeer-memory-core";

export const WATCHER_TRIGGER_ID = "iapeer-memory-memoryd";
/** LEGACY — the inbox-sweep timer id. The inbox pipeline is gone; this id is
 *  kept ONLY so update/verify can UNREGISTER a stale sweep trigger left on a
 *  host provisioned before the direct-to-canon migration (idempotent: the
 *  notifier treats not-found as a soft no-op). Never re-registered. */
export const LEGACY_SWEEP_TRIGGER_ID = "iapeer-memory-inbox-sweep";
/** Weekly DreamWeaver tick. A notifier TIMER straight to DreamWeaver, GATED
 *  by a check-script that runs the deterministic pre-filter (`dream-collect
 *  --gate`): a dead week never wakes anyone (Фаза «детерминированный
 *  предфильтр»). The Index is OFF the entry — it only finalises on
 *  DreamWeaver's consolidation report. */
export const DREAM_TRIGGER_ID = "iapeer-memory-dream-tick";
/** Default target of the weekly tick — the orchestrator (was `index`). */
export const DREAM_TARGET = "dreamweaver";
/** The inverted pipeline's first receiver of memoryd events: the scriber
 *  vets BEFORE placement and reports to the
 *  index; same-id re-registration REPLACES the trigger (notifier contract),
 *  so update/verify --repair re-target idempotently. */
export const DEFAULT_EVENT_TARGET = "scriber";

/** The watcher runs one executable file — a launcher wrapping the stable binary. */
export function launcherScriptContent(binaryPath: string): string {
  return [
    "#!/usr/bin/env bash",
    "# iapeer-memory memoryd launcher — the notifier watcher's script.",
    "# Generated by init; re-generated by verify --repair. The stable binary",
    "# path closes the «daemon on an evicted snapshot» defect class (ADR-010).",
    `exec "${binaryPath}" memoryd`,
    "",
  ].join("\n");
}

function writeExecutable(filePath: string, content: string): "written" | "identical" {
  try {
    if (fs.readFileSync(filePath, "utf-8") === content) return "identical";
  } catch {
    // absent — write
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const tmp = `${filePath}.tmp`;
  guardedWriteFileSync(tmp, content, "utf-8");
  fs.chmodSync(tmp, 0o755);
  fs.renameSync(tmp, filePath);
  return "written";
}

export function writeLauncherScript(opts: {
  launcherPath: string;
  binaryPath: string;
}): "written" | "identical" {
  return writeExecutable(opts.launcherPath, launcherScriptContent(opts.binaryPath));
}

/**
 * Dream-tick gate check-script (notifier `check` for the weekly timer): shells
 * the stable binary's REGISTRY-FREE gate. exit 0 ⇔ an in-window agent-memory
 * note exists (the notifier fires the tick), exit 1 ⇔ a dead week (nobody is
 * woken — true zero-LLM). It calls the binary (not baked bash) because the
 * gate reads the vault path from config.env, which the binary loads itself;
 * the notifier's env carries no IAPEER_MEMORY_* context.
 */
export function dreamGateScriptContent(binaryPath: string): string {
  return [
    "#!/usr/bin/env bash",
    "# iapeer-memory dream-tick gate — the notifier check for the weekly timer.",
    "# Generated by init; re-generated by verify --repair. exit 0 = work exists",
    "# (fire the tick), exit 1 = dead week (DreamWeaver is never woken).",
    `exec "${binaryPath}" dream-collect --gate`,
    "",
  ].join("\n");
}

export function writeDreamGateScript(opts: {
  dreamGateScriptPath: string;
  binaryPath: string;
}): "written" | "identical" {
  return writeExecutable(opts.dreamGateScriptPath, dreamGateScriptContent(opts.binaryPath));
}

/**
 * Declare the scriber an ephemeral worker (clean window per delivery,
 * M1/M2/M3 — core canon «wake_policy ephemeral»). The profile is a CORE
 * file: no-clobber merge of exactly one key, atomic write.
 */
export function patchWakePolicyEphemeral(
  peerCwd: string,
): "written" | "identical" | "missing-profile" {
  const profilePath = path.join(peerCwd, ".iapeer", "peer-profile.json");
  let profile: Record<string, unknown>;
  try {
    const raw = JSON.parse(fs.readFileSync(profilePath, "utf-8")) as unknown;
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) return "missing-profile";
    profile = raw as Record<string, unknown>;
  } catch {
    return "missing-profile";
  }
  if (profile.wake_policy === "ephemeral") return "identical";
  profile.wake_policy = "ephemeral";
  const tmp = `${profilePath}.tmp`;
  guardedWriteFileSync(tmp, `${JSON.stringify(profile, null, 2)}\n`, "utf-8");
  fs.renameSync(tmp, profilePath);
  return "written";
}

export function registrationMessage(opts: {
  script: string;
  target?: string;
  id?: string;
}): string {
  return JSON.stringify({
    script: opts.script,
    target: opts.target ?? DEFAULT_EVENT_TARGET,
    id: opts.id ?? WATCHER_TRIGGER_ID,
  });
}

/** Weekly DreamWeaver tick (Mondays 04:00 by default — the human sleeps).
 *  Targets the ORCHESTRATOR (DreamWeaver), GATED by the deterministic
 *  pre-filter (`check`): the message only lands on a week with real work. */
export function dreamTimerMessage(opts?: {
  cron?: string;
  target?: string;
  id?: string;
  dreamGateScriptPath?: string;
}): string {
  const body: {
    when: string;
    message: string;
    target: string;
    id: string;
    check?: string;
  } = {
    when: opts?.cron || "0 4 * * 1",
    message:
      "DREAM_TICK: weekly agent-memory consolidation — you orchestrate. Run " +
      "`iapeer-memory dream-collect` (read-only; the deterministic pre-filter " +
      "already found the work) and fan out one subagent per task in its " +
      "`tasks` — per your doctrine: each subagent only JUDGES the supplied " +
      "candidates and transcript files (it never discovers), touching only " +
      "in-window notes. Collect the subagents' results into ONE consolidation " +
      "report to the Index. A verb error = report it, do not guess the fleet.",
    target: opts?.target || DREAM_TARGET,
    id: opts?.id ?? DREAM_TRIGGER_ID,
  };
  if (opts?.dreamGateScriptPath) body.check = opts.dreamGateScriptPath;
  return JSON.stringify(body);
}

export type IapSendResult = {
  ok: boolean;
  detail: string;
  /** True when the test-sandbox fuse blocked the send — callers report a
   *  SKIP, not a failure (the iapeer `skipped-sandbox` precedent). */
  suppressed?: boolean;
};

/** Default registrant personality (trigger owner + event target). */
const DEFAULT_REGISTRANT = "index";

/** `--from` wants the full identity `<runtime>-<personality>`, never a bare
 *  name. The runtime is REQUIRED and MUST be the registrant's ACTUAL declared
 *  runtime (resolveRegistrantRuntime / the host-runtime onboard passed) — never
 *  assumed. A hardcoded "claude" here registered a codex role peer as
 *  `claude-index`, which the notifier refused ("runtime claude not declared for
 *  index"); the runtime now flows from the peer's declaration. */
export function fromIdentity(personality: string, runtime: string): string {
  return `${runtime}-${personality}`;
}

/** The registrant role peer's DECLARED runtime, read from the live registry
 *  (`iapeer list --json`: per-peer `default_runtime` is the canonical default,
 *  `runtimes[{runtime,status}]` the fallback). Returns null when the peer is
 *  absent or carries no declared runtime — the caller then SKIPS registration
 *  (degrade) instead of guessing a runtime. This is the single source of truth
 *  for the `--from` identity across init / update / verify / uninstall. */
export function resolveRegistrantRuntime(
  egress: Egress,
  opts: { iapeerBin?: string; registrant?: string } = {},
): string | null {
  const registrant = opts.registrant ?? DEFAULT_REGISTRANT;
  const bin = opts.iapeerBin ?? IAPEER_BIN;
  const proc = egress.spawnSync([bin, "list", "--json"], {
    explicitBin: opts.iapeerBin !== undefined,
  });
  if (proc.refused || proc.spawnError || proc.exitCode !== 0) return null;
  let rows: unknown;
  try {
    rows = JSON.parse(proc.stdout);
  } catch {
    return null;
  }
  if (!Array.isArray(rows)) return null;
  const row = rows.find(
    (r): r is { default_runtime?: unknown; runtimes?: unknown } =>
      typeof (r as { personality?: unknown })?.personality === "string" &&
      (r as { personality: string }).personality === registrant,
  );
  if (!row) return null;
  if (typeof row.default_runtime === "string" && row.default_runtime.trim()) {
    return row.default_runtime.trim();
  }
  if (Array.isArray(row.runtimes)) {
    for (const rt of row.runtimes) {
      const name = (rt as { runtime?: unknown })?.runtime;
      if (typeof name === "string" && name.trim()) return name.trim();
    }
  }
  return null;
}

function iapSend(
  egress: Egress,
  opts: {
    message: string;
    fromIdentity: string;
    /** Notifier peer to address: `watcher` (events) or `timer` (cron/sweep). */
    to?: "watcher" | "timer";
    iapeerBin?: string;
  },
): IapSendResult {
  // The hard fuse (prod Index: crashlooping temp-path
  // triggers; the notifier's sockets are host-global, no sandbox env contains a
  // real send) lives in the EGRESS CONSTRUCTOR now (deny-by-default §4):
  // under a test sandbox this handle refuses the spawn before it happens.
  const bin = opts.iapeerBin ?? IAPEER_BIN;
  const proc = egress.spawnSync(
    [bin, "send", opts.to ?? "watcher", "--from", opts.fromIdentity, "--message", opts.message],
    { explicitBin: opts.iapeerBin !== undefined },
  );
  if (proc.refused) {
    return { ok: false, suppressed: true, detail: "iap send suppressed (test sandbox)" };
  }
  if (proc.spawnError) {
    return { ok: false, detail: `${bin} unavailable: ${proc.spawnError}` };
  }
  if (proc.exitCode !== 0) {
    return {
      ok: false,
      detail: proc.stderr.trim() || `iapeer send exited ${proc.exitCode}`,
    };
  }
  // NB: a 0 exit code means DELIVERED, not "registration valid" — the
  // teaching reply goes to the registrant's session. Callers must confirm
  // via readWatcherTrigger.
  return { ok: true, detail: "delivered (confirm via the registrant's profile)" };
}

export function registerWatcher(
  egress: Egress,
  opts: {
    launcherPath: string;
    /** Registrant PERSONALITY (owner of the durable trigger + default target). */
    registrant?: string;
    /** Runtime prefix of the registrant's identity (claude for role peers). */
    runtime: string;
    target?: string;
    id?: string;
    iapeerBin?: string;
  },
): IapSendResult {
  const registrant = opts.registrant ?? DEFAULT_REGISTRANT;
  return iapSend(egress, {
    fromIdentity: fromIdentity(registrant, opts.runtime),
    iapeerBin: opts.iapeerBin,
    message: registrationMessage({
      script: opts.launcherPath,
      // No fallback to the registrant here: the EVENT target default
      // (scriber, inverted pipeline) lives in registrationMessage.
      target: opts.target,
      id: opts.id,
    }),
  });
}

export function unregisterWatcher(
  egress: Egress,
  opts: {
    registrant?: string;
    runtime: string;
    id?: string;
    iapeerBin?: string;
  },
): IapSendResult {
  return iapSend(egress, {
    fromIdentity: fromIdentity(opts.registrant ?? DEFAULT_REGISTRANT, opts.runtime),
    iapeerBin: opts.iapeerBin,
    message: JSON.stringify({ cmd: "unregister", id: opts.id ?? WATCHER_TRIGGER_ID }),
  });
}

/** Register a timer trigger (the weekly dream-tick) — body built by
 *  dreamTimerMessage(). */
export function registerTimer(
  egress: Egress,
  opts: {
    message: string;
    registrant?: string;
    runtime: string;
    iapeerBin?: string;
  },
): IapSendResult {
  return iapSend(egress, {
    to: "timer",
    fromIdentity: fromIdentity(opts.registrant ?? DEFAULT_REGISTRANT, opts.runtime),
    iapeerBin: opts.iapeerBin,
    message: opts.message,
  });
}

export function unregisterTimer(
  egress: Egress,
  opts: {
    id: string;
    registrant?: string;
    runtime: string;
    iapeerBin?: string;
  },
): IapSendResult {
  return iapSend(egress, {
    to: "timer",
    fromIdentity: fromIdentity(opts.registrant ?? DEFAULT_REGISTRANT, opts.runtime),
    iapeerBin: opts.iapeerBin,
    message: JSON.stringify({ cmd: "unregister", id: opts.id }),
  });
}

export type WatcherTrigger = {
  /** Durable role token: "event" (watcher) | "time" (timer) — notifier fact. */
  role: string;
  id: string;
  owner: string;
  target?: string;
  script?: string;
  /** Timer-only: the check-gate script path. */
  check?: string;
  heartbeatSec?: number;
  topic?: string;
};

/**
 * Read a durable trigger from the registrant's peer profile — the
 * canonical storage contract (sanctioned). Never throws.
 */
export function readWatcherTrigger(opts: {
  registrantCwd: string;
  id?: string;
  owner?: string;
  /** "event" (default, watcher triggers) or "time" (timers). */
  role?: "event" | "time";
}): WatcherTrigger | null {
  const id = opts.id ?? WATCHER_TRIGGER_ID;
  const owner = opts.owner ?? DEFAULT_REGISTRANT;
  const role = opts.role ?? "event";
  try {
    const profile = JSON.parse(
      fs.readFileSync(
        path.join(opts.registrantCwd, ".iapeer", "peer-profile.json"),
        "utf-8",
      ),
    ) as { notifier?: { triggers?: WatcherTrigger[] } };
    const triggers = profile.notifier?.triggers ?? [];
    return (
      triggers.find((t) => t.role === role && t.id === id && t.owner === owner) ??
      null
    );
  } catch {
    return null;
  }
}
